### ISSUE TITLE
Selection bounding box stops working. Tiles added go behind and won't show.

### ISSUE THREAD

**Issue by drswoboda** [DarKDinDoN/share-media#22]
I have a scene with 13 bounding tiles. It stops allowing the tile selection outline from highlighting. You can double-click the area to edit tiles. Also, the Tile Sort module will not highlight tiles. This usually happens after I close and come back. Once it stops working there is no fix.

Once this happens, then I cannot select or add any new normal Tiles. They always get blocked behind the bounding tiles.

I know this is a horrible description of my issue. I do have scenes that work and scenes that are broken. I can send you some exports if this will help debug. Or I can make a screen capture and show the issue in a video.

I love this module, it's fantastic for Theatre of the Mind... Please keep up the great work.
-David

**Comment by DarKDinDoN** [comment]
Hello David,

It does not sound like a Share Media issue.
Share Media create regular tiles. There are just "marked" with special tags so it can remember them as bounding tile.

Can you try again by disabling all modules (share media included)?
Then only with the share media (and libwrapper) module?

If the issue persists, please export a scene.

**Comment by drswoboda** [comment]
I will try that tonight. I did do some more testing and noticed that when I load the first tile created (the full background) the other tiles have selection issues. If I clear that tile, then all the highlights show up again. I will try your suggestions and reply back. Thank you.

**Comment by drswoboda** [comment]
I tried FindTheCulprit and the same issue happens with just the Share-Media module. Here is a link to a quick screencast of me showing the issue. Please let me know what else I can do to help with this issue.

link to video
https://1drv.ms/v/s!Ao8CrenVzI5LgP2pUX0UrTQRSBBSPhE?e=q8wQX4

**Comment by DarKDinDoN** [comment]
Hi David,

Thx for the detailed video. Really helped to understand the issue.

Unfortunately, I can't really fix the issue in V9.

Let me explain the issue:

Foundry as a layers system that Share Media leverages. 
It works, just like Gimp, Photoshop and alike.
Layers are ordered with fixed numbers (their own zIndex).

It goes like (in order):
- BackgroundLayer
- DrawingsLayer
- GridLayer
- TemplateLayer
- ...

The issue here is that there is no "TileLayer", Tiles are simply merged with the "BackgroundLayer" which also controls the background image of the map.

So the new "ShareMediaLayer" that displays images onto the map can be positioned (zIndex) either after the "BackgroundLayer" or before.

It is currently positionned after the "BackgroundLayer", thus hiding this layer (Map image and tiles).
And I can't really make it before the "BackgroundLayer", because this layer would hide the "ShareMediaLayer".


Now the good news!
Foundry V10 changes a lot about the layers system.
The issue should be fixed with V10.

**Comment by drswoboda** [comment]
Hello DarKDinDoN,

I'm glad to hear the video helped explain things, you know the old adage, a picture is worth 1000 words...
And thank you for the explanation of what is going on. So my takeaway at this point is that I should avoid swapping the background image out and just use the overlay portraits for now. I look forward to seeing what you change or add in v10 and I'm glad to hear that you will be bringing this to v10, that is great news.

I have a few other questions to ask, and I'm not sure in which forum to ask them. Is here okay?

Let me ask one now. Can the manual operation of selecting the UI on an image be triggered from a Macro? I'd like to have a macro in a journal, that swaps in a portrait to a slot with just a macro click and avoid the multi-step process of the UI selection process. Is this possible?

Great work, thanks.

**Comment by DarKDinDoN** [comment]
Hi,
There is an API that allows you to create macros here: https://github.com/DarKDinDoN/share-media/blob/main/API.md

Example: 
This share all token's actor image in a popout to all players

```js
const API = game.modules.get('share-media').API;
const tokens = game.canvas.tokens.controlled;

if (!tokens.length) return;

for (token of tokens) {
    API.sharePopoutMediaToAll(token.actor.data.img);
}
```

For your specific situation, I'll to think about an API method that allows you to share on a scene without selecting a bouding tile.

**Comment by DarKDinDoN** [comment]
@drswoboda 

The API was updated with the capability of using macros without displaying any bounding tiles selection dialogs.

Here is an example: 

```js
const API = game.modules.get('share-media').API;
API.shareSceneMediaCover(url, false, true, "Stage 1")
```

**Comment by drswoboda** [comment]
Thank you for adding this new option to the API. I think it will be a great addition.
